services:
  - docker

before_install:
  - docker build -t dockerbasic -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerbasic npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-northeast-1"
  app: "docker-basic"
  env: "Dockerbasic-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-038044210180"
  bucket_path: "docker-basic"
  on:
    branch: master